apache/skywalking-php

- docs/en/contribution/compiling.md
Refer to <https://lists.apache.org/thread/p2nl038c4zz5vbr9n6h9ozzcbgnww7q7>.
> Update compiling project document.

- .github/workflows/rust.yml
- README.md
- Vagrantfile
- docs/README.md
- docs/en/setup/service-agent/php-agent/Supported-list.md
- src/channel.rs
- src/plugin/mod.rs
- src/plugin/plugin_pdo.rs
- tests/data/expected_context.yaml
- tests/e2e.rs
- tests/php/fpm/pdo.php
1. For <https://www.php.net/manual/en/book.pdo.php>.
2. To fix the bug `no buffer space available (os error 55)` on MacOS, so switch unix datagram to stream.
> Add PDO plugin, and switch unix datagram to stream.

- README.md
Make the creation of issue clearer.
> Update readme about creating issue.

- src/plugin/plugin_memcached.rs
- src/plugin/plugin_pdo.rs
- src/plugin/plugin_predis.rs
- src/plugin/plugin_redis.rs
- src/tag.rs
- tests/data/expected_context.yaml
- tests/php/fpm/memcached.php
https://skywalking.apache.org/docs/main/next/en/setup/service-agent/virtual-cache/
> Adapt virtual cache.

- Cargo.lock
- Cargo.toml
- src/module.rs
- src/util.rs
- src/worker.rs
Mentioned in https://github.com/apache/skywalking/discussions/9943#discussioncomment-4108549 .
I found this is because the php-fpm manager process is run under root, but pool processes is run under other user.
So I fix it by change the socket file mode to `0777`.
> Fix permission denied of unix socket.

- .github/workflows/pecl.yml
- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- src/errors.rs
- src/execute.rs
- src/lib.rs
- src/module.rs
- src/plugin/plugin_curl.rs
- src/plugin/plugin_memcached.rs
- src/plugin/plugin_pdo.rs
- src/plugin/plugin_predis.rs
- src/plugin/plugin_redis.rs
- src/request.rs
- src/util.rs
- src/worker.rs
I noticed that PHP 8.2 was released on December 08, 2022. So add it in
https://www.php.net/archive/2022.php#2022-12-08-1
> Support PHP 8.2

- src/plugin/mod.rs
- src/worker.rs
Fix https://github.com/apache/skywalking/issues/10240.
> Fix php-fpm freeze after large amount of request.

- .github/workflows/rust.yml
Retry one time for cargo test.
> Retry cargo test when failed in CI.

- docs/en/setup/service-agent/php-agent/README.md
- src/lib.rs
- src/module.rs
- src/worker.rs
1. Add configuration option `skywalking_agent.authentication`.
2. Update document.
> Add authentication support.

- Cargo.lock
- Cargo.toml
- src/module.rs
Because `tracing-appender` may panic when it is created, such as permission denied, so remove it and create the log file by myself.
> Avoid potential panic for logger.

- src/plugin/plugin_curl.rs
Fix https://github.com/apache/skywalking/issues/10424.
> Fix the curl plugin hook curl_setopt by mistake.

- Cargo.lock
- Cargo.toml
- scripts/Cargo.toml
- src/plugin/plugin_curl.rs
- src/plugin/plugin_memcached.rs
- src/plugin/plugin_mysqli.rs
- src/plugin/plugin_pdo.rs
- src/plugin/plugin_predis.rs
- src/plugin/plugin_redis.rs
- src/request.rs
- src/worker.rs
1. Upgrade dependencies.
2. Adapt to `skywalking-rust`.
> Upgrade dependencies and adapt the codes.

- Cargo.lock
- Cargo.toml
- dist-material/LICENSE
- src/execute.rs
- src/plugin/plugin_amqplib.rs
- src/plugin/plugin_curl.rs
- src/plugin/plugin_predis.rs
- src/plugin/plugin_redis.rs
- src/plugin/plugin_swoole.rs
The crate `phper` has released the new version 0.11.0, so upgrade it.
> Upgrade and adapt phper.

- src/plugin/plugin_pdo.rs
- src/request.rs
1. Canonicalize unknown port to `0`.
2. Canonicalize unknown addr to `unknown:0`.
3. Canonicalize unknown uri to `/unknown`.
> Canonicalize unknown.

- README.md
> Polish doc about Swoole

- Cargo.lock
- Cargo.toml
- dist-material/LICENSE
- scripts/Cargo.toml
- src/context.rs
- src/plugin/mod.rs
- src/plugin/plugin_amqplib.rs
- src/plugin/plugin_curl.rs
- src/plugin/plugin_memcached.rs
- src/plugin/plugin_mongodb.rs
- src/plugin/plugin_mysqli.rs
- src/plugin/plugin_pdo.rs
- src/plugin/plugin_predis.rs
- src/plugin/plugin_redis.rs
- src/request.rs
- src/worker.rs
Upgrade dependencies and license.
> Upgrade dependencies.

- src/execute.rs
The error log is missing some key fields, which makes it difficult to troubleshoot the issue. Now I will add them.
> Add more info for error log.

- .github/workflows/pecl.yml
- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- dist-material/LICENSE
https://github.com/apache/skywalking/issues/12409
> Add feature sasl for rdkafka

- src/plugin/plugin_swoole.rs
Refer to https://github.com/apache/skywalking/discussions/12812
> Adapt to `Swoole\Http\Server`

- Cargo.lock
- Cargo.toml
- dist-material/LICENSE
- src/module.rs
Fix https://github.com/apache/skywalking/discussions/12908
> Fix tracing time
