config.m4
src/channel.rs
src/exception_frame.rs
src/lib.rs
src/plugin/plugin_pdo.rs
tests/data/expected_context.yaml
tests/php/fpm/pdo.php

A non-blocking sender fails with `EAGAIN`. And a `call_user_function` (`zend_call_function`) fails when exception is set.

Save PDO exceptions.

---

.github/workflows/rust.yml
README.md
docs/en/setup/service-agent/php-agent/README.md

Because our CI tests PHP version is greater than or equal to 7.2 (Many composer dependencies need PHP 7.2+).

Update minimal supported PHP version to 7.2.

---

src/plugin/plugin_mysqli.rs
src/plugin/plugin_pdo.rs
src/plugin/plugin_predis.rs

The request id is used for swoole, it's OK in fpm if it's None, but it will not work in swoole, so fix it.

Add missing request_id.

---

docs/en/contribution/compiling.md

I was facing Rustc error as 1.65+ is required. And I find out there is no rust 1.65 on brew(https://formulae.brew.sh/formula/rust). 
So, I have to follow Rust release blog(https://blog.rust-lang.org/2022/11/03/Rust-1.65.0.html), and use `rustup update stable` command to upgrade the rust version

Make explicit rust version requirement

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
rust-toolchain.toml
scripts/Cargo.toml
src/module.rs
src/plugin/plugin_memcached.rs
src/plugin/plugin_redis.rs
src/request.rs
src/worker.rs

Lock the rust version to prevent the new version feature from being applied, resulting in the failure to compile the minimum version 1.65 of rust.

Lock develop rust version to 1.65, upgrade deps.

---

src/module.rs
src/worker.rs

Fix worker unexpected shutdown problem mentioned in:
https://github.com/apache/skywalking/discussions/10260
https://github.com/apache/skywalking/discussions/10109
@burque98 @jmt33
The reason is that when the `pm` mode used by php-fpm is dynamic or ondemand, when the pool process exits, `MSHUTDOWN` will be called, and this hook will kill the worker process.
Now this action is removed, replace with `libc::prctl(libc::PR_SET_PDEATHSIG, libc::SIGTERM);`.

Fix worker unexpected shutdown.

---

docs/en/contribution/compiling.md
docs/en/setup/service-agent/php-agent/README.md

It is very unfriendly to use `rustup` to install Rust globally, so use standalone installer instead.
However, if it is a non-global installation, `rustup` is a good choice.

Update docs about installing rust.

---

src/plugin/plugin_mysqli.rs

Hack the destructor to remove the global hash map value hold by the object id key, to cleanup resources.
This is done for other plugins, only mysqli is left.

Hack dtor for mysqli to cleanup resources.

---

docs/en/setup/service-agent/php-agent/README.md
src/lib.rs
src/module.rs
src/util.rs
src/worker.rs

1. Add configuration option `skywalking_agent.runtime_dir`, indicate the runtime directory for holding sock files now.
2. Update the document about option.

Add configuration option `skywalking_agent.runtime_dir`.

---

.github/workflows/rust.yml
.rustfmt.toml
Cargo.lock
Cargo.toml
docs/en/setup/service-agent/php-agent/README.md
src/lib.rs
src/module.rs
src/worker.rs
tests/common/mod.rs

1. Add config option skywalking_agent.enable_tls, skywalking_agent.ssl_trusted_ca_path, skywalking_agent.ssl_key_path, skywalking_agent.ssl_cert_chain_path.
2. Remove `http://` scheme in `skywalking_agent.server_addr`.

Support TLS.

---

docs/en/setup/service-agent/php-agent/README.md
src/lib.rs
src/module.rs
src/worker.rs

Periodic reporting instance properties.

---

Cargo.lock
Cargo.toml
dist-material/LICENSE
src/module.rs
src/request.rs

1. Previously, the `SKYWALKING_AGENT_ENABLE` was only used in the module hook, if disabled, there is an error log for each request.
This PR make the `SKYWALKING_AGENT_ENABLE` work in the request hook as well.
2. Start 0.5.0 dev.

Make the `SKYWALKING_AGENT_ENABLE` work in the request hook as well.

---

src/plugin/plugin_curl.rs
tests/common/mod.rs
tests/data/expected_context.yaml
tests/e2e.rs
tests/php/fpm/curl-multi.enter.php

1. Although the curl plugin has been available , but support for `curl_multi_*` api was missing, it has now been added.
2. Refactor the code of curl plugin, to achieve the effect of multiplexing.

Support tracing `curl_multi_*` api.

---

src/context.rs
src/errors.rs
src/plugin/plugin_curl.rs
src/request.rs
tests/common/mod.rs
tests/data/expected_context.yaml
tests/php/fpm/curl-multi.enter.php
tests/php/fpm/curl.enter.php
tests/php/swoole/main.1.php

1. Fix parent endpoint and peer in segment ref. In the past, the parent endpoint and peer of the sw8 header uses the endpoint and peer of the exit span by mistake (but it does not seem to affect the display of tracing on the UI).
3. Fix tag url in entry span.

Fix parent endpoint and peer in segment ref and tag url in entry span.

---

package.tpl.xml
scripts/src/command/create_package_xml.rs

The inclusion of XML in template variables is not in line with best practice, so refactoring it.

Refactor script create_package_xml.

---

src/plugin/plugin_predis.rs
tests/data/expected_context.yaml

1. Previous the predis plugin hook the `AbstractConnection.executeCommand` method, which is too low level, it doesn't look good on the display as endpoint, now change to hook `Client.<OP>`.
2. To adapt old version predis, so not mark getting not-exists key error.

Refactor predis plugin to hook Client.

---

src/plugin/plugin_pdo.rs

When using doctrine the return type of PDO->prepare is Doctrine\DBAL\Driver\PDO\Statement and the hook didn't work. Changed the if to a match statement and added a bunch of debug statements. Fixed a minor typo.

Fix hook for Doctrine PDO class

---

src/plugin/mod.rs
src/plugin/plugin_amqplib.rs
src/plugin/plugin_curl.rs
src/plugin/plugin_memcached.rs
src/plugin/plugin_mysqli.rs
src/plugin/plugin_pdo.rs
src/plugin/plugin_predis.rs
src/plugin/plugin_redis.rs
tests/data/expected_context.yaml

1. Log `Exception` after calling the hooked function/method, if it throw.
2. Add `PDO::__construct` and `mysqli::__construct` in spans, because they are possible to throw Exception.

Log Exception in tracing span when throw.

---

Cargo.lock
Cargo.toml
dist-material/LICENSE
scripts/Cargo.toml
src/context.rs
src/module.rs
src/plugin/mod.rs
src/plugin/plugin_amqplib.rs
src/plugin/plugin_curl.rs
src/plugin/plugin_memcached.rs
src/plugin/plugin_mysqli.rs
src/plugin/plugin_pdo.rs
src/plugin/plugin_predis.rs
src/plugin/plugin_redis.rs
src/request.rs
tests/data/expected_context.yaml

1. As `skywalking-rust` released, switch to use `AsyncSpan` api in hooking `curl_multi_exec`.
2. Disable `chrono` default features to fix <https://github.com/apache/skywalking-php/security/dependabot/10>.
3. Other dependencies have no break changes.

Upgrade dependencies and adapt.

---

docs/en/setup/service-agent/php-agent/README.md

1. Minimal required rust version is `1.65`.
2. Notice user to run `php-fpm` in foreground.

Fix required rust version and add runing php-fpm notice in docs.

---

src/plugin/plugin_redis.rs

Fix https://github.com/apache/skywalking/issues/10996

Fix the situation where the redis port is string.

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
README.md
build.rs
dist-material/LICENSE
docker-compose.yml
docs/en/configuration/ini-settings.md
docs/en/configuration/zend-observer.md
docs/menu.yml
src/execute.rs
src/lib.rs
src/module.rs
src/plugin/mod.rs
src/plugin/plugin_pdo.rs
src/plugin/plugin_predis.rs
src/tag.rs
tests/common/mod.rs
tests/data/expected_context.yaml
tests/e2e.rs

According to <https://www.datadoghq.com/blog/engineering/php-8-observability-baked-right-in/>, the observer API in PHP 8, being able to work well with jit is a more recommended approach in PHP 8.
Therefore, add a switch to selectively enable zebd observer support for PHP 8.

Optionally enable zend observer api for auto instrumentation.

---

src/plugin/plugin_redis.rs

Fix the first error mention in https://github.com/apache/skywalking/issues/11041
> thread '' panicked at 'called Result::unwrap() on an Err value: Any { .. }', src/plugin/plugin_redis.rs:361:44

Fix the empty span situation in redis after hook.

---

src/plugin/plugin_memcache.rs
src/plugin/plugin_mysqli.rs
src/plugin/style.rs
tests/data/expected_context.yaml
tests/e2e.rs
tests/php/fpm/mysqli.php

1. Refactor mysqli plugin, getting peer by properties, rather than hacking by `MYSQL_MAP`.
2. Support both OO and procedural apis.

Refactor mysqli plugin, support procedural api.

---

src/context.rs
src/plugin/plugin_amqplib.rs
src/plugin/plugin_curl.rs
tests/data/expected_context.yaml

Previous the target address in cross process header is the peer of entry span, which is wrong, now fix it.

Fix target address in cross process header.

---

Cargo.lock
Cargo.toml
dist-material/LICENSE
dist-material/LICENSE.tpl

1. Release SkyWalking PHP 0.7.0.
2. Remove `skywalking-php` itself in dependencies LICENSES.

Release SkyWalking PHP 0.7.0

---

Cargo.lock
Cargo.toml
dist-material/LICENSE
scripts/Cargo.toml
worker/Cargo.toml

This pull request includes updates to various dependencies across multiple `Cargo.toml` files. The changes primarily involve updating the versions of several dependencies to their latest versions.
Dependency updates:
* Updated `hostname` from `0.4.0` to `0.4.1` in `Cargo.toml`
* Updated `once_cell` from `1.21.1` to `1.21.3` in `Cargo.toml` and `worker/Cargo.toml` [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L58-R82) [[2]](diffhunk://#diff-68efb2e92ef637adfc679d138884adddb0379af94d13e49767102c548859444fL35-R44)
* Updated `phper` from `0.15.1` to `0.16.0` in `Cargo.toml`
* Updated `skywalking` from `0.8.0` to `0.9.0` in `Cargo.toml` and `worker/Cargo.toml` [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L58-R82) …

Updated skywalking dependency

---

Cargo.lock
Cargo.toml

This pull request includes a version update for the `Cargo.toml` file, changing the version from "1.0.0-dev" to "1.0.0".
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L24-R24): Updated the version from "1.0.0-dev" to "1.0.0".

Bump version to 1.0.0 for release

---

.github/workflows/rust.yml

The actions-rs org has been archived for years at this point and it doesn't look like it's coming back. For security reasons we are going to remove it from the list of allowed actions in the org soon. (See https://github.com/apache/infrastructure-actions)

chore(ci): Replace archived actions-rs actions
